# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agenda/aba_agenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 1061))
        self.frame.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 1px;\n"
"box-shadow: 5px 5px 5px;\n"
"border-color:  rgb(149, 149, 149);")
        self.frame.setObjectName("frame")
        self.dashboard_button = QtWidgets.QPushButton(self.frame)
        self.dashboard_button.setGeometry(QtCore.QRect(20, 200, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button.setFont(font)
        self.dashboard_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashboard_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("agenda\\../Source/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_button.setIcon(icon)
        self.dashboard_button.setIconSize(QtCore.QSize(50, 50))
        self.dashboard_button.setObjectName("dashboard_button")
        self.clientes_button = QtWidgets.QPushButton(self.frame)
        self.clientes_button.setGeometry(QtCore.QRect(20, 300, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clientes_button.setFont(font)
        self.clientes_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clientes_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("agenda\\../Source/cliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clientes_button.setIcon(icon1)
        self.clientes_button.setIconSize(QtCore.QSize(40, 40))
        self.clientes_button.setObjectName("clientes_button")
        self.funcionarios_button = QtWidgets.QPushButton(self.frame)
        self.funcionarios_button.setGeometry(QtCore.QRect(20, 400, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.funcionarios_button.setFont(font)
        self.funcionarios_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.funcionarios_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("agenda\\../Source/funcionarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.funcionarios_button.setIcon(icon2)
        self.funcionarios_button.setIconSize(QtCore.QSize(40, 40))
        self.funcionarios_button.setObjectName("funcionarios_button")
        self.agenda_button = QtWidgets.QPushButton(self.frame)
        self.agenda_button.setGeometry(QtCore.QRect(20, 500, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.agenda_button.setFont(font)
        self.agenda_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.agenda_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("agenda\\../Source/agenda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agenda_button.setIcon(icon3)
        self.agenda_button.setIconSize(QtCore.QSize(50, 50))
        self.agenda_button.setObjectName("agenda_button")
        self.relatorios_button = QtWidgets.QPushButton(self.frame)
        self.relatorios_button.setGeometry(QtCore.QRect(20, 600, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.relatorios_button.setFont(font)
        self.relatorios_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.relatorios_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("agenda\\../Source/relatorios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.relatorios_button.setIcon(icon4)
        self.relatorios_button.setIconSize(QtCore.QSize(50, 50))
        self.relatorios_button.setObjectName("relatorios_button")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 10, 191, 181))
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setPixmap(QtGui.QPixmap("agenda\\../Source/Cenicos.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(299, -1, 1621, 131))
        self.frame_2.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 40, 256, 51))
        self.textBrowser_2.setAutoFillBackground(False)
        self.textBrowser_2.setStyleSheet("border: 0px;\n"
"color:rgb(29, 41, 61);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(300, 130, 1631, 931))
        self.frame_3.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(50, 60, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(202,68,69);\n"
"border-radius:17px;\n"
"color: white;\n"
"text-align:center;\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("agenda\\mais_icon.png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.frame_3)
        self.calendarWidget_2.setGeometry(QtCore.QRect(440, 160, 1151, 651))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.calendarWidget_2.setFont(font)
        self.calendarWidget_2.setToolTip("")
        self.calendarWidget_2.setStyleSheet("QCalendarWidget QAbstractItemView{background-color: white;\n"
"}\n"
"QCalendarWidget QToolButton{background-color: transparent; color: rgb(0, 0, 0); hight: 10px;\n"
"}\n"
"QCalendarWidget QAbstractItemView:item:selected{background-color:rgb(156, 10, 18); border-radius: 5px; color: white;\n"
"}\n"
"QCalendarWidget QWidget{ background-color: white;\n"
"}\n"
"")
        self.calendarWidget_2.setSelectedDate(QtCore.QDate(2026, 2, 13))
        self.calendarWidget_2.setGridVisible(True)
        self.calendarWidget_2.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget_2.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.LongDayNames)
        self.calendarWidget_2.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_2.setNavigationBarVisible(False)
        self.calendarWidget_2.setDateEditEnabled(True)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_3)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 190, 361, 261))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("QCalendarWidget QAbstractItemView{background-color: white;\n"
"}\n"
"QCalendarWidget QToolButton{background-color: transparent; color: rgb(0, 0, 0); ;\n"
"}\n"
"QCalendarWidget QAbstractItemView:item:selected{background-color:rgb(156, 10, 18); border-radius: 5px; color: white;\n"
"}\n"
"QCalendarWidget QWidget{ background-color: white;\n"
"}")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(30, 480, 361, 281))
        self.frame_4.setStyleSheet("background-color: white;\n"
"border-radius: 20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(40, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(70, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(70, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(70, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.widget_2 = QtWidgets.QWidget(self.frame_4)
        self.widget_2.setGeometry(QtCore.QRect(40, 100, 16, 16))
        self.widget_2.setStyleSheet("background-color: rgb(255, 100, 103); border-radius:5px;")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.frame_4)
        self.widget_3.setGeometry(QtCore.QRect(40, 140, 16, 16))
        self.widget_3.setStyleSheet("background-color: rgb(80, 162, 255); border-radius:5px;")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.frame_4)
        self.widget_4.setGeometry(QtCore.QRect(40, 180, 16, 16))
        self.widget_4.setStyleSheet("background-color: rgb(0, 212, 146); border-radius:5px;")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.frame_4)
        self.widget_5.setGeometry(QtCore.QRect(40, 220, 16, 16))
        self.widget_5.setStyleSheet("background-color: rgb(255, 185, 0); border-radius:5px;")
        self.widget_5.setObjectName("widget_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(440, 60, 1151, 151))
        self.frame_5.setStyleSheet("background-color: white;\n"
"border-radius: 40px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(880, 30, 231, 51))
        self.frame_6.setStyleSheet("background-color:rgb(247, 247, 247);\n"
"border-radius:15px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_5.setGeometry(QtCore.QRect(166, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setStyleSheet("color:rgb(156, 10, 18);\n"
"background-color: white;\n"
"border-radius: 10px;")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_2.setGeometry(QtCore.QRect(88, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("color: rgb(141, 141, 141); border-radius: 10px;")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton = QtWidgets.QToolButton(self.frame_6)
        self.toolButton.setGeometry(QtCore.QRect(17, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setWeight(50)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("color: rgb(141, 141, 141); border-radius: 10px;")
        self.toolButton.setObjectName("toolButton")
        self.frame_5.raise_()
        self.pushButton.raise_()
        self.calendarWidget_2.raise_()
        self.calendarWidget.raise_()
        self.frame_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashboard_button.setText(_translate("MainWindow", "Dashboard"))
        self.clientes_button.setText(_translate("MainWindow", "Clientes"))
        self.funcionarios_button.setText(_translate("MainWindow", "Funcionários"))
        self.agenda_button.setText(_translate("MainWindow", "Agenda"))
        self.relatorios_button.setText(_translate("MainWindow", "Documentos"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Agenda</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Novo Agendamento"))
        self.label.setText(_translate("MainWindow", "Legenda"))
        self.label_3.setText(_translate("MainWindow", "Ensaios"))
        self.label_4.setText(_translate("MainWindow", "Apresentações"))
        self.label_5.setText(_translate("MainWindow", "Oficinas"))
        self.label_6.setText(_translate("MainWindow", "Reuniões"))
        self.label_2.setText(_translate("MainWindow", "fevereiro 2026"))
        self.toolButton_5.setText(_translate("MainWindow", "Mês"))
        self.toolButton_2.setText(_translate("MainWindow", "Semana"))
        self.toolButton.setText(_translate("MainWindow", "Dia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
