# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'documentos/aba_documentos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1085)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 1061))
        self.frame.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 1px;\n"
"box-shadow: 5px 5px 5px;\n"
"border-color:  rgb(149, 149, 149);")
        self.frame.setObjectName("frame")
        self.dashboard_button = QtWidgets.QPushButton(self.frame)
        self.dashboard_button.setGeometry(QtCore.QRect(20, 200, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button.setFont(font)
        self.dashboard_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashboard_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("documentos\\../Source/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_button.setIcon(icon)
        self.dashboard_button.setIconSize(QtCore.QSize(50, 50))
        self.dashboard_button.setObjectName("dashboard_button")
        self.clientes_button = QtWidgets.QPushButton(self.frame)
        self.clientes_button.setGeometry(QtCore.QRect(20, 300, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clientes_button.setFont(font)
        self.clientes_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clientes_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("documentos\\../Source/cliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clientes_button.setIcon(icon1)
        self.clientes_button.setIconSize(QtCore.QSize(40, 40))
        self.clientes_button.setObjectName("clientes_button")
        self.funcionarios_button = QtWidgets.QPushButton(self.frame)
        self.funcionarios_button.setGeometry(QtCore.QRect(20, 400, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.funcionarios_button.setFont(font)
        self.funcionarios_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.funcionarios_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("documentos\\../Source/funcionarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.funcionarios_button.setIcon(icon2)
        self.funcionarios_button.setIconSize(QtCore.QSize(40, 40))
        self.funcionarios_button.setObjectName("funcionarios_button")
        self.agenda_button = QtWidgets.QPushButton(self.frame)
        self.agenda_button.setGeometry(QtCore.QRect(20, 500, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.agenda_button.setFont(font)
        self.agenda_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.agenda_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("documentos\\../Source/agenda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agenda_button.setIcon(icon3)
        self.agenda_button.setIconSize(QtCore.QSize(50, 50))
        self.agenda_button.setObjectName("agenda_button")
        self.relatorios_button = QtWidgets.QPushButton(self.frame)
        self.relatorios_button.setGeometry(QtCore.QRect(20, 600, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.relatorios_button.setFont(font)
        self.relatorios_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.relatorios_button.setStyleSheet("text-align: left;\n"
"color: rgb(139, 139, 139);\n"
"padding-left: 10px;\n"
"border-radius:10px;\n"
"hover-color {\n"
"    background-color:rgb(254, 242, 242 solid);\n"
"    color:rgb(159, 7, 18);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("documentos\\../Source/relatorios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.relatorios_button.setIcon(icon4)
        self.relatorios_button.setIconSize(QtCore.QSize(50, 50))
        self.relatorios_button.setObjectName("relatorios_button")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 10, 191, 181))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap("documentos\\../Source/Cenicos.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(299, -1, 1621, 131))
        self.frame_2.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 40, 256, 51))
        self.textBrowser_2.setAutoFillBackground(False)
        self.textBrowser_2.setStyleSheet("border: 0px;\n"
"color:rgb(29, 41, 61);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(300, 130, 1631, 931))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(30, 120, 1461, 500))
        self.frame_6.setStyleSheet("background-color:white;\n"
"border-radius: 30px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 20, 71, 51))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius: 14px;")
        self.pushButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("documentos\\../Source/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius: 14px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setGeometry(QtCore.QRect(960, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_4.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius: 14px;")
        self.pushButton_4.setShortcut("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setGeometry(QtCore.QRect(1140, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_5.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius: 14px;")
        self.pushButton_5.setShortcut("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setGeometry(QtCore.QRect(1320, 20, 71, 51))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius: 14px;")
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("documentos\\../Source/filtro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(1280, 30, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: white;\n"
"border-radius: 14px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("documentos\\../Source/upload_icon.png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(30, 30, 511, 61))
        self.frame_4.setStyleSheet("background-color: white;\n"
"border-radius: 14px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 11, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(20, 11, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("documentos\\../Source/utilizador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon8)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setAutoFillBackground(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("documentos\\../Source/fiscal_icon.png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon9)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashboard_button.setText(_translate("MainWindow", "Dashboard"))
        self.clientes_button.setText(_translate("MainWindow", "Clientes"))
        self.funcionarios_button.setText(_translate("MainWindow", "Funcionários"))
        self.agenda_button.setText(_translate("MainWindow", "Agenda"))
        self.relatorios_button.setText(_translate("MainWindow", "Documentos"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Documentos</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Buscar por nome do Arquivo ou Proprietário..."))
        self.pushButton_4.setText(_translate("MainWindow", "Todos os Anos"))
        self.pushButton_5.setText(_translate("MainWindow", "Todos os Meses"))
        self.pushButton_7.setText(_translate("MainWindow", "Anexar Documentos"))
        self.pushButton_2.setText(_translate("MainWindow", "Funcionários"))
        self.pushButton.setText(_translate("MainWindow", "Clientes"))
        self.pushButton_8.setText(_translate("MainWindow", "Fiscais"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
